language: node_js

node_js:
  - lts/*

before_script:
  - git clone https://github.com/zowiegong/hexo-theme-os.git themes/os
  - npm install hexo-renderer-jade

script: yarn build

# deploy
deploy:
  provider: pages
  skip_cleanup: true
  keep_history: true
  target_branch: gh-pages
  local_dir: public
  github_token: ${GITHUB_TOKEN}
  on:
    branch: master

# SEO search engine ping
after_deploy:
  - curl https://www.google.com/ping?sitemap=https://lollollollollol.com/sitemap.xml
  - curl https://www.bing.com/ping?sitemap=https://lollollollollol.com/sitemap.xml
  - curl -X POST 'http://ping.baidu.com/ping/RPC2' --header "Content-Type:text/xml" -d "<?xml version="1.0"?><methodCall><methodName>weblogUpdates.ping</methodName><params><param><value><string>https://lollollollollol.com/atom.xml</string></value></param><param><value><string>https://lollollollollol.com/atom.xml</string></value></param></params></methodCall>"
  - curl -X POST 'http://ping.baidu.com/ping/RPC2' --header "Content-Type:text/xml" -d "<?xml version="1.0"?><methodCall><methodName>weblogUpdates.ping</methodName><params><param><value><string>https://lollollollollol.com/sitemap.xml</string></value></param><param><value><string>https://lollollollollol.com/sitemap.xml</string></value></param></params></methodCall>"
  - curl 'https://pingomatic.com/ping/?title=lollollollollol&blogurl=https%3A%2F%2Flollollollollol.com&rssurl=https%3A%2F%2Flollollollollol.com%2Fatom.xml&chk_blogs=on&chk_feedburner=on&chk_tailrank=on&chk_superfeedr=on'
